### ISSUE TITLE
BUG: UNC paths aren't resolved correctly

### ISSUE THREAD

**Issue by bitbay** [gulpjs/glob-stream#120]
Can't use a remote network path on windows, globs aren't resolved correctly.

Given an existing remote resource
```
C:\Users\user>dir /B \\192.168.1.2\fle.txt
file.txt
```
`src()` fails to access it correctly.

### What were you expecting to happen?
Remote `file.txt` correctly copied to `./local'.

### What actually happened?
No file was copied

### Please give us a sample of your gulpfile
```js
// CASE A: using forward slashes
const remoteFile = '//192.168.1.2/file.txt';
src(remoteFile).dest('./local');
```
```js
// CASE B using (escaped) backward slashes
const remoteFile = '\\\\192.168.1.2\\file.txt';
src(remoteFile).dest('./local');
```

### Terminal output / screenshots
```sh
# CASE A
Error: File not found with singular glob: //192.168.1.2/file.txt (if this was purposeful, use `allowEmpty` option)
at Glob.<anonymous> (D:\testing\node_modules\glob-stream\readable.js:84:17)
...
```
```sh
# CASE B
Error: File not found with singular glob: D:/testing/\\192.168.1.2\file.txt (if this was purposeful, use `allowEmpty` option)
at Glob.<anonymous> (D:\testing\node_modules\glob-stream\readable.js:84:17)
...
```
### Please provide the following information:
* Windows 10
* node version (run `node -v`): v14.21.2
* npm version (run `npm -v`): 6.14.17
* gulp version (run `gulp -v`): CLI version: 2.3.0
Local version: 4.0.2

**Comment by phated** [comment]
@bitbay we had some bugs with absolute paths that were solved in 8.0.2 - I'm not sure if they were also causing your problems with UNC paths. I don't have a good way to test that, so could you give 8.0.2 a try?
