### ISSUE TITLE
Please update to latest glob

### ISSUE THREAD

**Issue by NekR** [gulpjs/glob-stream#65]
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Which causes this:

```
[19:59:48] Starting 'zip'...
[19:59:49] 'zip' errored after 1.51 s
[19:59:49] RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at globUnescape (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/minimatch/minimatch.js:919:12)
    at Minimatch.parse (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/minimatch/minimatch.js:618:12)
    at Array.map (native)
    at Minimatch.<anonymous> (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/minimatch/minimatch.js:174:14)
    at Array.map (native)
    at Minimatch.make (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/minimatch/minimatch.js:173:13)
    at new Minimatch (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/minimatch/minimatch.js:128:8)
    at setopts (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/common.js:112:20)
    at new Glob (/$REPLACED$/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:117:3)
```

**Comment by phated** [comment]
Switch to gulp 4

**Comment by NekR** [comment]
I'm on gulp 4. Can you open this back now?

**Comment by phated** [comment]
Duplicate of https://github.com/gulpjs/glob-stream/issues/57

**Comment by NekR** [comment]
Hmm.. So you say just don't use gulp now?

**Comment by phated** [comment]
@NekR what does that mean?  Someone needs to look into glob 6 breaking changes to see if we can upgrade.  Locking.
